import type { DB } from "./types";

export const SEED: DB = {
  contest: {
    target: 8,
    // Prize unset by default — the contest banner shows evergreen placeholder
    // copy until an admin enters this year's confirmed prize in Settings.
    prize: "",
  },
  builders: [
    {
      id: "b_brije",
      name: "Brije Homes",
      initials: "BH",
      color: "#116799",
      featured: true,
      phone: "(407) 794-0000",
      website: "brije.com",
      years: 0,
      blurb:
        "Award-winning custom home builder serving Central Florida with a design-first, client-focused building process. Brije Homes' 2026 Parade entry is The Aspen — a 5,552 sq ft modern farmhouse on 12 acres in Morriston.",
      ad: "2026 Featured Builder showcasing The Aspen — a modern farmhouse on 12 acres with an AI-powered smart home, resort-style pool, and outdoor living.",
    },
    {
      id: "b_dr_horton",
      name: "D.R. Horton",
      initials: "DRH",
      color: "#1a2858",
      featured: false,
      phone: "352-421-1730",
      website: "www.drhorton.com/florida/west-central-florida",
      years: 0,
      blurb:
        "Showcasing the Holden model at Tartan Farms at Winding Oaks for the 2026 Parade of Homes.",
      ad: "Standard Builder Entry - Holden at Tartan Farms at Winding Oaks.",
    },
    {
      id: "b_deltona",
      name: "The Deltona Corporation",
      initials: "DC",
      color: "#f28a20",
      featured: false,
      phone: "352-347-2322",
      website: "deltona.com",
      years: 0,
      blurb:
        "Premier Builder Entry showcasing the Mustang model in Marion Oaks.",
      ad: "Premier Builder Entry - Mustang in Marion Oaks.",
    },
    {
      id: "b_secure_built",
      name: "Secure Built, LLC",
      initials: "SB",
      color: "#d62027",
      featured: false,
      phone: "352-671-9140",
      website: "securebuilt.com",
      years: 0,
      blurb:
        "Custom home builder showcasing the Rutherford Farmhouse in Irish Acres.",
      ad: "Standard Builder Entry - Rutherford Farmhouse in Irish Acres.",
    },
    {
      id: "b_curington",
      name: "Curington Homes",
      initials: "CH",
      color: "#8a6d3b",
      featured: false,
      phone: "352-401-9707",
      website: "curingtonhomes.com",
      years: 0,
      blurb:
        "Ocala custom home builder showcasing the Sebastian VIII Craftsman Edition in Irish Acres.",
      ad: "Premier Builder Entry - Sebastian VIII Craftsman Edition in Irish Acres.",
    },
    {
      id: "b_ferrer",
      name: "Ferrer Construction",
      initials: "FC",
      color: "#2f5d8a",
      featured: false,
      phone: "352-297-2287",
      website: "ferrerbuilder.com",
      years: 0,
      blurb:
        "Ocala custom home builder participating in the 2026 Parade of Homes. Model details coming soon.",
      ad: "Premier Builder Entry - 2026 Parade of Homes.",
    },
    {
      id: "b_luetgert",
      name: "Luetgert Development Corp",
      initials: "LD",
      color: "#0a6e4f",
      featured: false,
      phone: "352-369-8300",
      website: "luetgertdev.com",
      years: 0,
      blurb:
        "Ocala luxury builder showcasing the Golden Hills spec home in Golden Hills & Country Club.",
      ad: "Standard Builder Entry - Golden Hills in Golden Hills & Country Club.",
    },
    {
      id: "b_otow",
      name: "On Top of the World",
      initials: "OW",
      color: "#1f4e8c",
      featured: false,
      phone: "866-228-5878",
      website: "ontopoftheworldcommunities.com",
      years: 0,
      blurb:
        "Ocala's premier master-planned community showcasing The Whitmore — a 2,870 sq ft spec home in Balfour with two master suites, a gourmet kitchen, and a pool with sundeck.",
      ad: "Standard Builder Entry - The Whitmore in Balfour at On Top of the World.",
    },
    {
      id: "b_calesa",
      name: "Calesa Township",
      initials: "CT",
      color: "#c8791f",
      featured: false,
      phone: "352-353-2112",
      website: "MyCalesa.com",
      years: 0,
      blurb:
        "Innovative master-planned Ocala community presenting The Heritage — a 1,551 sq ft spec home in Perlino Grove with an open great room, laundry suite, and whole-house fresh air exchange.",
      ad: "Additional Home Entry - The Heritage in Perlino Grove at Calesa Township.",
    },
    {
      id: "b_townsley",
      name: "Townsley Construction",
      initials: "TC",
      color: "#5b3a8a",
      featured: false,
      phone: "352-270-1199",
      website: "townsleyconstruction.com",
      years: 0,
      blurb:
        "Ocala custom home builder showcasing The Wyrick II — a 2,655 sq ft custom home with four bedrooms, a hidden butler's pantry, and open-concept living.",
      ad: "Standard Builder Entry - The Wyrick II custom home.",
    },
    {
      id: "b_stentiford",
      name: "Stentiford Construction",
      initials: "SC",
      color: "#2f6f4f",
      featured: false,
      phone: "352-266-8994",
      website: "stentifordfl.com",
      years: 0,
      blurb:
        "Ocala builder showcasing the Fort King Townhome — a 1,513 sq ft, three-bedroom spec townhome near downtown Ocala.",
      ad: "Premier Builder Entry - Fort King Townhome.",
    },
    {
      id: "b_almilton",
      name: "A.L. Milton Construction",
      initials: "AM",
      color: "#8a5a2f",
      featured: false,
      phone: "352-816-0886",
      website: "almilton.com",
      years: 0,
      blurb:
        "Ocala builder showcasing the Hemlock D — a 1,454 sq ft Craftsman-style semi-custom home in Silver Springs Shores.",
      ad: "Standard Builder Entry - Hemlock D.",
    },
    {
      id: "b_dream_custom",
      name: "Dream Custom Homes of Citrus",
      initials: "DC",
      color: "#3a5a8a",
      featured: false,
      phone: "727-259-4891",
      website: "dreamcustomhomes.com",
      years: 0,
      blurb:
        "Award-winning Citrus County builder showcasing the Don Valencia — a 3,521 sq ft semi-custom home in Pine Ridge Estates, Beverly Hills.",
      ad: "Standard Builder Entry - Don Valencia.",
    },
  ],
  neighborhoods: [
    {
      id: "n_on_top_of_the_world",
      name: "On Top of the World",
      city: "Ocala",
      color: "#1f4e8c",
      img: "",
      blurb:
        "Premier master-planned Ocala community — home to On Top of the World's Whitmore model in Balfour for the 2026 Parade.",
      low: 827780,
      high: 827780,
    },
    {
      id: "n_calesa_township",
      name: "Calesa Township",
      city: "Ocala",
      color: "#c8791f",
      img: "",
      blurb:
        "Innovative master-planned Ocala community — home to Calesa Township's Heritage model in Perlino Grove for the 2026 Parade.",
      low: 284000,
      high: 284000,
    },
    {
      id: "n_golden_hills",
      name: "Golden Hills & Country Club",
      city: "Ocala",
      color: "#0a6e4f",
      img: "",
      blurb:
        "Northwest Ocala golf community — home to Luetgert Development's Golden Hills spec home for the 2026 Parade.",
      low: 1400000,
      high: 1995000,
    },
    {
      id: "n_tartan_farms",
      name: "Tartan Farms at Winding Oaks",
      city: "Ocala",
      color: "#1a2858",
      img: "/parade-entries/2026/dr-horton-holden-home.jpg",
      blurb:
        "Ocala subdivision featuring D.R. Horton's two-story Holden model for the 2026 Parade.",
      low: 416990,
      high: 416990,
    },
    {
      id: "n_marion_oaks",
      name: "Marion Oaks",
      city: "Ocala",
      color: "#f28a20",
      img: "/parade-entries/2026/deltona-mustang-home.jpg",
      blurb:
        "Southwest Ocala community represented by The Deltona Corporation's Mustang model.",
      low: 350000,
      high: 350000,
    },
    {
      id: "n_irish_acres",
      name: "Irish Acres",
      city: "Ocala",
      color: "#d62027",
      img: "/parade-entries/2026/secure-built-rutherford-home.jpg",
      blurb:
        "Ocala acreage setting for Secure Built's Rutherford Farmhouse and Curington's Sebastian VIII Craftsman custom homes.",
      low: 615000,
      high: 699000,
    },
    {
      id: "n_brije_morriston",
      name: "Morriston",
      city: "Morriston",
      color: "#116799",
      img: "/parade-entries/2026/brije-home.png",
      blurb:
        "Twelve-acre countryside setting in Morriston showcasing Brije Homes' custom Aspen modern farmhouse, the 2026 Featured Builder entry.",
      low: 2750000,
      high: 3200000,
    },
    {
      id: "n_ocala",
      name: "Ocala",
      city: "Ocala",
      color: "#5b6b7a",
      img: "",
      blurb:
        "Custom and one-off model homes located across Ocala, outside the master-planned communities.",
      low: 560000,
      high: 560000,
    },
    {
      id: "n_pine_ridge",
      name: "Pine Ridge Estates",
      city: "Beverly Hills",
      color: "#3a5a8a",
      img: "",
      blurb:
        "Custom-home community in Beverly Hills, Citrus County.",
      low: 510290,
      high: 510290,
    },
  ],
  homes: [
    {
      id: "h_dr_horton_holden",
      color: "#2563a8",
      name: "Holden",
      builder: "b_dr_horton",
      nb: "n_tartan_farms",
      style: "Spec Home",
      price: 416990,
      beds: 4,
      baths: 3,
      sqft: 3313,
      garage: 2,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: true,
      x: 32,
      y: 50,
      blurb:
        "A two-story, all concrete block spec home in Tartan Farms at Winding Oaks with an open first floor, covered lanai, and smart home technology.",
      features: [
        "Model location: 4416 SW 69th St, Ocala, FL 34474",
        "Open-concept first floor",
        "Covered lanai",
        "Stainless steel dishwasher, electric range, and microwave",
        "2-car garage",
        "10-year RWC home warranty",
        "Smart home technology",
        "Quartz countertops",
        "Luxury vinyl plank flooring in main living areas",
        "Sliding glass door to outdoor patio",
      ],
      imgs: [
        "/parade-entries/2026/dr-horton-holden-home.jpg",
        "/parade-entries/2026/dr-horton-logo.png",
        "/parade-entries/2026/dr-horton-holden-floor-plan.png",
        "/parade-entries/2026/dr-horton-holden-home.jpg",
      ],
    },
    {
      id: "h_deltona_mustang",
      color: "#e07b1a",
      name: "Mustang",
      builder: "b_deltona",
      nb: "n_marion_oaks",
      style: "Spec Home",
      price: 350000,
      beds: 4,
      baths: 2,
      sqft: 2067,
      garage: 2,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: true,
      x: 54,
      y: 65,
      blurb:
        "The Mustang model in Marion Oaks pairs practical living space with upgraded finishes throughout the main living areas.",
      features: [
        "Model location: 356 Marion Oaks Trail, Ocala, FL 34473",
        "Quartz countertops",
        "Tiled shower and tiled tub surround",
        "Luxury vinyl plank flooring throughout main living area",
        "Irrigation system",
        "Garage door opener",
        "Maverick 10-year structural warranty",
        "Wood cabinets with soft-close feature",
        "Large inside laundry room with cabinets",
        "Kitchen island and spacious primary bedroom",
      ],
      imgs: [
        "/parade-entries/2026/deltona-mustang-home.jpg",
        "/parade-entries/2026/deltona-logo.jpg",
        "/parade-entries/2026/deltona-mustang-home.jpg",
        "/parade-entries/2026/deltona-mustang-home.jpg",
      ],
    },
    {
      id: "h_secure_built_rutherford",
      color: "#c0392b",
      name: "Rutherford Farmhouse",
      builder: "b_secure_built",
      nb: "n_irish_acres",
      style: "Custom Home",
      price: 679000,
      beds: 3,
      baths: 3,
      sqft: 2530,
      garage: 2,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: true,
      x: 75,
      y: 38,
      blurb:
        "Modern farmhouse meets country living in Irish Acres, with open living spaces, a chef's kitchen, and an oversized lanai.",
      features: [
        "Model location: 1764 NW 85th Loop, Ocala, FL 34475",
        "Price as shown: $679,000 - $699,000",
        "3 bedrooms, 3 bathrooms, 2-car garage, and office",
        "Open living area with deep coffered tray ceiling",
        "Chef's kitchen with quartz countertops and walk-in pantry",
        "Owner's suite with large island in closet",
        "Spa bath with soaking tub and dual shower",
        "Oversized lanai with pool bath access",
        "Oversized 2-car garage",
        "Secure Built 2-10 warranty",
      ],
      imgs: [
        "/parade-entries/2026/secure-built-rutherford-home.jpg",
        "/parade-entries/2026/secure-built-logo.png",
        "/parade-entries/2026/secure-built-rutherford-home.jpg",
        "/parade-entries/2026/secure-built-rutherford-home.jpg",
      ],
    },
    {
      id: "h_brije_aspen",
      color: "#b8860b",
      name: "The Aspen",
      builder: "b_brije",
      nb: "n_brije_morriston",
      style: "Custom Home",
      price: 2750000,
      beds: 4,
      baths: 5,
      sqft: 5552,
      garage: 4,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: true,
      x: 18,
      y: 28,
      blurb:
        "Brije Homes' 2026 Featured Builder showcase — a 5,552 sq ft modern farmhouse set on 12 acres in Morriston, with a grand floor-to-ceiling-window entry, AI-powered smart home technology, and a resort-style pool and outdoor living space.",
      features: [
        "Model location: 14951 SE 60th St, Morriston, FL 32668",
        "Price as shown with upgrades (without lot): $2,750,000",
        "8,073 sq ft total under roof on 12 acres",
        "Grand entry with floor-to-ceiling windows",
        "Great family room with fireplace",
        "Walk-in butler's pantry and a dedicated freedom room",
        "AI-powered smart home",
        "Zen outdoor garden",
        "Laundry room inside the primary suite",
        "Pool and outdoor living space",
        "Dual 2-car garages (4 cars)",
      ],
      imgs: [
        "/parade-entries/2026/brije-home.png",
        "/parade-entries/2026/brije-home.png",
        "/parade-entries/2026/brije-home.png",
      ],
    },
    {
      id: "h_curington_sebastian",
      color: "#7d4ba0",
      name: "Sebastian VIII Craftsman Edition",
      builder: "b_curington",
      nb: "n_irish_acres",
      style: "Custom Home",
      price: 615000,
      beds: 4,
      baths: 2,
      sqft: 2322,
      garage: 2,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: false,
      x: 70,
      y: 44,
      blurb:
        "A craftsman-style custom home in Irish Acres with elevated ceilings, oversized windows and doors, a luxury kitchen and baths, and a serene split floor plan.",
      features: [
        "Model location: 8214 NW 17th Circle, Ocala, FL 34475",
        "3,235 sq ft total under roof",
        "Elevated ceilings",
        "Oversized windows & doors",
        "Craftsman charm",
        "Luxury kitchen & baths",
        "Serene master retreat",
        "Cozy electric fireplace",
        "Elegant wood-look tile flooring",
        "Thoughtful split floor plan with walk-in pantry",
      ],
      imgs: [],
    },
    {
      id: "h_luetgert_golden_hills",
      color: "#1f8a5b",
      name: "Golden Hills",
      builder: "b_luetgert",
      nb: "n_golden_hills",
      style: "Spec Home",
      price: 1400000,
      beds: 4,
      baths: 3.5,
      sqft: 2812,
      garage: 3,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: false,
      x: 24,
      y: 22,
      blurb:
        "A luxury spec home in Golden Hills & Country Club with vaulted ceilings, custom cabinetry, stone countertops, architectural stained wood beams, and a custom summer kitchen.",
      features: [
        "Model location: 5395 NW 76th Court, Ocala, FL 34482",
        "4,604 sq ft total under roof · listed for sale at $1,995,000",
        "Luxury architectural design with vaulted ceilings",
        "Custom cabinetry & Crysttallo Oro stone countertops",
        "Architectural stained wood beams & exterior wood ceilings",
        "Poplar wood trim throughout",
        "Professionally designed landscape & hardscape",
        "Gas and wood-burning fireplaces",
        "Custom summer kitchen",
        "Listing agent: Hanna Pieri, Newgate Realty, LLC",
      ],
      imgs: [],
    },
    {
      id: "h_otow_whitmore",
      color: "#1f4e8c",
      name: "The Whitmore",
      builder: "b_otow",
      nb: "n_on_top_of_the_world",
      style: "Spec Home",
      price: 827780,
      beds: 3,
      baths: 3,
      sqft: 2870,
      garage: 3,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: false,
      x: 50,
      y: 50,
      blurb:
        "On Top of the World's 2026 model — a 2,870 sq ft spec home in Balfour with two master suites, a gourmet kitchen with a waterfall countertop and full stone backsplash, a flex room, and a pool with sundeck.",
      features: [
        "Model location: 8122 SW 102nd Ave, Ocala, FL 34481",
        "4,026 sq ft total under roof",
        "Extended covered & screened lanai",
        "Two master suites",
        "Gourmet kitchen with waterfall countertop & full stone backsplash",
        "Flex room",
        "Pool with sundeck",
        "Quality steel reinforced concrete block construction",
        "Whole-house fresh air exchange for improved air quality",
        "50-gallon natural gas water heater",
      ],
      imgs: [],
    },
    {
      id: "h_calesa_heritage",
      color: "#c8791f",
      name: "The Heritage",
      builder: "b_calesa",
      nb: "n_calesa_township",
      style: "Spec Home",
      price: 284000,
      beds: 3,
      baths: 2.5,
      sqft: 1551,
      garage: 2,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: false,
      x: 50,
      y: 50,
      blurb:
        "Calesa Township's 2026 model — a 1,551 sq ft two-story spec home in Perlino Grove with an open great room, dining room, laundry suite, and whole-house fresh air exchange.",
      features: [
        "Model location: 5626 SW 72nd Court, Ocala, FL 34474",
        "2,063 sq ft total under roof",
        "Great room & dining room",
        "Covered entry",
        "2-car garage",
        "First floor tile, second floor carpet",
        "Stairway baluster",
        "Laundry suite",
        "Whole-house fresh air exchange for improved air quality",
        "50-gallon electric water heater",
      ],
      imgs: [],
    },
    {
      id: "h_townsley_wyrick",
      color: "#5b3a8a",
      name: "The Wyrick II",
      builder: "b_townsley",
      nb: "n_ocala",
      style: "Custom Home",
      price: 560000,
      beds: 4,
      baths: 3,
      sqft: 2655,
      garage: 3,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: false,
      x: 50,
      y: 50,
      blurb:
        "Townsley Construction's 2026 custom home — a 2,655 sq ft residence with four bedrooms, a hidden butler's pantry, open-concept living, and a private primary suite retreat.",
      features: [
        "Model location: 2405 SE 36th Ave, Ocala, FL 34471",
        "3,949 sq ft total under roof",
        "4 spacious bedrooms",
        "3 modern baths with stylish finishes",
        "3-car garage with abundant storage",
        "Hidden butler's pantry",
        "Open-concept living for easy entertaining",
        "Private primary suite retreat",
        "Custom home — not for sale",
      ],
      imgs: [],
    },
    {
      id: "h_stentiford_fortking",
      name: "Fort King Townhome",
      color: "#2f6f4f",
      builder: "b_stentiford",
      nb: "n_ocala",
      style: "Townhome",
      price: 310000,
      beds: 3,
      baths: 2.5,
      sqft: 1513,
      garage: 1,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: false,
      x: 50,
      y: 50,
      blurb:
        "Stentiford Construction's 2026 Parade entry — a 1,513 sq ft townhome near downtown Ocala with three bedrooms, 2.5 baths, and a one-car garage. Professionally staged spec home.",
      features: [
        "Model location: 49 SE 15th Terrace, Ocala, FL 34471",
        "1,833 sq ft total under roof",
        "3 bedrooms",
        "2.5 baths",
        "1-car garage",
        "Spec home — professionally staged",
      ],
      imgs: [],
    },
    {
      id: "h_almilton_hemlock",
      name: "Hemlock D",
      color: "#8a5a2f",
      builder: "b_almilton",
      nb: "n_ocala",
      style: "Semi-Custom Home",
      price: 244900,
      beds: 3,
      baths: 2,
      sqft: 1454,
      garage: 2,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: false,
      x: 50,
      y: 50,
      blurb:
        "A.L. Milton Construction's 2026 Parade entry — a 1,454 sq ft Craftsman-style semi-custom home in Silver Springs Shores with three bedrooms, two baths, and a two-car garage.",
      features: [
        "Model location: 22 Almond Way, Ocala, FL 34472",
        "Subdivision: Silver Springs Shores",
        "2,086 sq ft total under roof",
        "Craftsman-style elevation with dormer and columns",
        "Large covered front and back porches",
        "Open main living area with cathedral ceilings",
        "Soft-close cabinets and quartz countertops",
        "Master with walk-in closet and tray ceiling",
        "Upgraded LVP flooring and shower tile",
      ],
      imgs: [],
    },
    {
      id: "h_dream_valencia",
      name: "Don Valencia",
      color: "#3a5a8a",
      builder: "b_dream_custom",
      nb: "n_pine_ridge",
      style: "Semi-Custom Home",
      price: 510290,
      beds: 4,
      baths: 3,
      sqft: 3521,
      garage: 3,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: false,
      x: 50,
      y: 50,
      blurb:
        "Dream Custom Homes' 2026 Parade entry — a 3,521 sq ft semi-custom home in Pine Ridge Estates, Beverly Hills, with four bedrooms, three baths, and a three-car garage. A multiple Parade of Homes winner.",
      features: [
        "Model location: 4302 N Canarywood Terrace, Beverly Hills, FL 34465",
        "Subdivision: Pine Ridge Estates",
        "4,757 sq ft total under roof",
        "Multiple Parade of Homes winner",
        "Elegant modern masterpiece",
      ],
      imgs: [],
    },
  ],
  sponsors: [
    {
      id: "sp_bennett",
      name: "Bennett Custom Homes",
      tier: "gold",
      color: "#8a6d3b",
      cat: "Full Page Ad · Custom Home Builder",
      img: "",
      website: "",
      phone: "",
      email: "",
      address: "",
    },
    {
      id: "sp_kitchenwise_closetwise",
      name: "Kitchen Wise | Closet Wise",
      tier: "silver",
      color: "#aeb47c",
      cat: "Half Page Ad Sponsor",
      img: "/parade-entries/2026/kitchen-wise-closet-wise-logo.jpg",
      website: "https://kitchenwise.com/greater-ocala",
      phone: "352-758-2650",
      email: "agoodger@kitchenwise.com",
      address: "2816 CR 523, I-3, Wildwood, FL 34785",
    },
  ],
  faqs: [
    {
      q: "When is the 2026 Parade of Homes?",
      a: "The 2026 MCBIA Parade of Homes is scheduled for November 6-8 and November 13-15 across Marion County.",
    },
    {
      q: "Is admission free?",
      a: "Yes. The Parade of Homes is free and open to the public.",
    },
    {
      q: "Where can I find the homes?",
      a: "Use the Homes and Map pages to browse the current 2026 entries. Additional entries and assets will be added as they are received.",
    },
    {
      q: "Who is the featured builder for 2026?",
      a: "[Brije Homes](https://www.brije.com/) is the 2026 Featured Builder. Also named the 2025 Marion County Builder of the Year and recognized with multiple 2025 Parade of Homes awards, Brije Homes creates custom homes with quality craftsmanship and a personalized building experience, helping families across Central Florida build with confidence.",
    },
  ],
  users: [],
  submissions: [],
  notifications: [],
};

export const BUILDER_ENTRIES = [
  {
    id: "entry_stentiford_fortking",
    createdAt: new Date("2026-08-07T08:22:00-04:00"),
    status: "NEW",
    contactName: "Tyler Stentiford",
    contactPhone: "352-572-0453",
    contactEmail: "tyler@stentifordfl.com",
    builderName: "Stentiford Construction",
    builderContact: "Paul Stentiford",
    builderPhone: "352-266-8994",
    builderEmail: "tyler@stentifordfl.com",
    website: "https://www.stentifordfl.com/",
    officeAddress: "201 NE 8th Avenue, Ocala, FL 34470",
    license: "CGC061626",
    modelName: "Fort King Townhome",
    sqftLiving: "1513",
    sqftTotal: "1833",
    beds: "3",
    baths: "2.5",
    garage: "1 Car",
    subdivision: "No",
    modelAddress: "49 SE 15th Terrace, Ocala, FL 34471",
    price: "$310,000",
    buildType: "Spec Home",
    staged: "Yes",
    entryLevel: "PREMIER BUILDER ENTRY (Members) - $5,000",
    paymentMethod: "Check",
    signature: "",
    billingName: "Paul Stentiford",
    receiptEmail: null,
    billingAddress: null,
    frontElevation: null,
    logo: null,
    floorPlan: null,
    details: {
      entryId: "2486",
      total: "5150",
      featuresNote: "Features to be sent by Tyler.",
      features: [],
      subcontractors: [
        { service: "Cabinets", name: "Deem's Cabinetry" },
        { service: "Windows", name: "Central Florida Window" },
        { service: "Plumbing", name: "Chad's Water Works" },
        { service: "Lumber", name: "Romac" },
        { service: "Geotech", name: "Geotechnical Engineering" },
        { service: "Glass Enclosures", name: "ARP" },
      ],
    },
  },
  {
    id: "entry_otow_whitmore",
    createdAt: new Date("2026-08-05T17:20:00-04:00"),
    status: "NEW",
    contactName: "Katie Miller",
    contactPhone: "352-789-4377",
    contactEmail: "katie_miller@colenbuilt.net",
    builderName: "On Top of the World",
    builderContact: "On Top of the World",
    builderPhone: "866-228-5878",
    builderEmail: "info@otow.net",
    website: "ontopoftheworldcommunities.com",
    officeAddress: "8447 SW 99th Street Rd, Ocala, FL 34481",
    license: "CGC1505760",
    modelName: "The Whitmore",
    sqftLiving: "2870",
    sqftTotal: "4026",
    beds: "3",
    baths: "3",
    garage: "3 Car",
    subdivision: "Balfour",
    modelAddress: "8122 SW 102nd Ave, Ocala, FL 34481",
    price: "$827,780",
    buildType: "Spec Home",
    staged: "Yes",
    entryLevel: "STANDARD BUILDER ENTRY (Members) - $2,500",
    paymentMethod: "American Express",
    signature: "",
    billingName: "Linda Massarella",
    receiptEmail: "katie_miller@colenbuilt.net",
    billingAddress: "8445 SW 80th Street, Ocala, FL 34481",
    frontElevation: null,
    logo: null,
    floorPlan: null,
    details: {
      entryId: "2481",
      total: "2575",
      findingInstructions:
        "From I-75, take Exit 350 (SR 200) southwest 6.5 miles. Turn right at SW 99th Street Road.",
      features: [
        "Extended Covered & Screened Lanai",
        "Two Master Suites",
        "Gourmet Kitchen",
        "Waterfall Kitchen Countertop",
        "Full Stone Backsplash",
        "Flex Room",
        "Pool with Sundeck",
        "Quality steel reinforced concrete block construction",
        "Whole-house fresh air exchange for improved air quality",
        "50-gallon natural gas water heater",
      ],
    },
  },
  {
    id: "entry_calesa_heritage",
    createdAt: new Date("2026-08-06T14:22:00-04:00"),
    status: "NEW",
    contactName: "Katie Miller",
    contactPhone: "352-789-4377",
    contactEmail: "katie_miller@colenbuilt.net",
    builderName: "Calesa Township",
    builderContact: "Calesa Township",
    builderPhone: "352-353-2112",
    builderEmail: "info@mycalesa.net",
    website: "MyCalesa.com",
    officeAddress: "6404 SW 78th Court, Ocala, FL 34474",
    license: "CGC1505760",
    modelName: "The Heritage",
    sqftLiving: "1551",
    sqftTotal: "2063",
    beds: "3",
    baths: "2.5",
    garage: "2 Car",
    subdivision: "Perlino Grove",
    modelAddress: "5626 SW 72nd Court, Ocala, FL 34474",
    price: "$284,000",
    buildType: "Spec Home",
    staged: "Yes",
    entryLevel:
      "ADDITIONAL HOME ENTRY (Only after your first home entry is submitted) - $2,000",
    paymentMethod: "American Express",
    signature: "",
    billingName: "Linda Massarella",
    receiptEmail: "katie_miller@colenbuilt.net",
    billingAddress: "8445 SW 80th St, Ocala, FL 34481",
    frontElevation: null,
    logo: null,
    floorPlan: null,
    details: {
      entryId: "2485",
      total: "2060",
      findingInstructions: "We will advise once they reach our Sales Center.",
      features: [
        "Great Room",
        "Dining Room",
        "Covered Entry",
        "2 Car Garage",
        "First Floor Tile",
        "Second Floor Carpet",
        "Stairway Baluster",
        "Laundry Suite",
        "Whole-house fresh air exchange for improved air quality",
        "50 gallon electric water heater",
      ],
    },
  },
  {
    id: "entry_townsley_wyrick",
    createdAt: new Date("2026-08-06T14:22:00-04:00"),
    status: "NEW",
    contactName: "Josh McDermott",
    contactPhone: "352-270-1199",
    contactEmail: "jmcdermott@townsleyconstruction.comm",
    builderName: "Townsley Construction",
    builderContact: "Josh McDermott",
    builderPhone: "352-270-1199",
    builderEmail: "townsleyconstruction@gmail.com",
    website: "townsleyconstruction.com",
    officeAddress: "2405 Southeast 36th Avenue, Ocala, FL 34471",
    license: "CGC1524085",
    modelName: "The Wyrick II",
    sqftLiving: "2655",
    sqftTotal: "3949",
    beds: "4",
    baths: "3",
    garage: "3",
    subdivision: "No",
    modelAddress: "2405 Southeast 36th Avenue, Ocala, FL 34471",
    price: "$560,000.00",
    buildType: "Custom Home",
    staged: "Yes",
    entryLevel: "STANDARD BUILDER ENTRY (Members) - $2,500",
    paymentMethod: "Check",
    signature: "",
    billingName: "Ann McDermott",
    receiptEmail: null,
    billingAddress: null,
    frontElevation: null,
    logo: null,
    floorPlan: null,
    details: {
      entryId: "2484",
      total: "2575",
      listPrice: "Not for Sale",
      features: [
        "4 spacious bedrooms for family, guests, or an office.",
        "3 modern baths with stylish finishes.",
        "3-car garage with abundant storage.",
        "Hidden butler's pantry.",
        "Open-concept living for easy entertaining.",
        "Sleek kitchen designed for gathering.",
        "Private primary suite retreat.",
        "Bright interiors with natural light.",
      ],
      subcontractors: [
        { service: "Gas & Plumbing", name: "Allen Curry" },
        { service: "Garage Doors", name: "D&D Garage Doors" },
        { service: "Marketing Video", name: "Bad to the Drone" },
        { service: "Landscape", name: "Grandview Landscaping Services" },
        { service: "Floor Materials", name: "Bowen Tile" },
        { service: "Redi-Mix Concrete", name: "Del Zotto" },
      ],
    },
  },
  {
    id: "entry_dr_horton_holden",
    createdAt: new Date("2026-07-30T11:30:00-04:00"),
    status: "APPROVED",
    contactName: "Jennifer McKathan",
    contactPhone: "352-266-4104",
    contactEmail: "jrmckathan@drhorton.com",
    builderName: "D.R. Horton",
    builderContact: "Jennifer McKathan",
    builderPhone: "352-421-1730",
    builderEmail: "jrmckathan@drhorton.com",
    website: "https://www.drhorton.com/florida/west-central-florida",
    officeAddress: "3300 Southwest 34th Avenue, Ocala, FL 34474",
    license: "CRC057592",
    modelName: "Holden",
    sqftLiving: "3313",
    sqftTotal: "3313",
    beds: "4",
    baths: "3",
    garage: "2",
    subdivision: "Tartan Farms at Winding Oaks",
    modelAddress: "4416 SW 69th St, Ocala, FL 34474",
    price: "$416,990",
    buildType: "Spec Home",
    staged: "Yes",
    entryLevel: "STANDARD BUILDER ENTRY (Members) - $2,500",
    paymentMethod: "Check",
    signature:
      "https://mcbia.org/index.php?gf-signature=6a6b6e1eca2244.06361588&form-id=47&field-id=41&hash=d84c3f3c02f75d84d69a8b94aaeb8f9847e5d299a207d2de0fdb0bc681cca6e3",
    billingName: "Jennifer McKathan",
    receiptEmail: null,
    billingAddress: null,
    frontElevation: "/parade-entries/2026/dr-horton-holden-home.jpg",
    logo: "/parade-entries/2026/dr-horton-logo.png",
    floorPlan: "/parade-entries/2026/dr-horton-holden-floor-plan.png",
    details: {
      entryId: "2456",
      total: "2575",
      features: [
        "Two-story all concrete block home",
        "Open-concept first floor",
        "Covered lanai",
        "Stainless steel dishwasher, electric range, and microwave",
        "2-car garage",
        "10-year RWC home warranty",
        "Smart home technology",
        "Quartz countertops",
        "Luxury vinyl plank flooring in main living areas",
        "Sliding glass door to outdoor patio",
      ],
    },
  },
  {
    id: "entry_deltona_mustang",
    createdAt: new Date("2026-07-27T13:15:00-04:00"),
    status: "APPROVED",
    contactName: "Sara Jackson",
    contactPhone: "352-533-1122",
    contactEmail: "sara.jackson@deltona.com",
    builderName: "The Deltona Corporation",
    builderContact: null,
    builderPhone: "352-347-2322",
    builderEmail: "sara.jackson@deltona.com",
    website: "www.deltona.com",
    officeAddress: "8014 Southwest 135th Street Road, Ocala, FL 34473",
    license: "cbc1261181",
    modelName: "Mustang",
    sqftLiving: "2067",
    sqftTotal: "2786",
    beds: "4",
    baths: "2",
    garage: "2",
    subdivision: "Marion Oaks",
    modelAddress: "356 Marion Oaks Trail, Ocala, FL 34473",
    price: "$350,000",
    buildType: "Spec Home",
    staged: "Yes",
    entryLevel: "PREMIER BUILDER ENTRY (Members) - $5,000",
    paymentMethod: "Credit Card",
    signature:
      "https://mcbia.org/index.php?gf-signature=6a679076039bd5.58424747&form-id=47&field-id=41&hash=82916a52f7f651402382930ad5ed535a848145f29618f6c68f4bfdad75f110c1",
    billingName: "Victoria Pollard",
    receiptEmail: null,
    billingAddress: "8014 Southwest 135th Street Road, Ocala, FL 34473",
    frontElevation: "/parade-entries/2026/deltona-mustang-home.jpg",
    logo: "/parade-entries/2026/deltona-logo.jpg",
    floorPlan: null,
    details: {
      entryId: "2448",
      total: "5150",
      features: [
        "Quartz countertops",
        "Tiled shower and tiled tub surround",
        "Luxury vinyl plank flooring throughout main living area",
        "Irrigation system",
        "Garage door opener",
        "Maverick 10-year structural warranty",
        "Wood cabinets with soft-close feature",
        "Large inside laundry room with cabinets",
        "Kitchen island",
        "Spacious primary bedroom",
      ],
    },
  },
  {
    id: "entry_secure_built_rutherford",
    createdAt: new Date("2026-07-22T10:03:00-04:00"),
    status: "APPROVED",
    contactName: "Nicole Cortez",
    contactPhone: "352-817-5358",
    contactEmail: "nicole@securebuilt.com",
    builderName: "Secure Built, LLC",
    builderContact: "Ryan Gummer",
    builderPhone: "352-671-9140",
    builderEmail: "ryan@securebuilt.com",
    website: "www.securebuilt.com",
    officeAddress: "1764 NW 85th Loop, Ocala, FL 34475",
    license: "CRC1331562",
    modelName: "Rutherford Farmhouse",
    sqftLiving: "2530",
    sqftTotal: "3775",
    beds: "3",
    baths: "3",
    garage: "2",
    subdivision: "Irish Acres",
    modelAddress: "1764 NW 85th Loop, Ocala, FL 34475",
    price: "$679,000 - $699,000",
    buildType: "Custom Home",
    staged: "Yes",
    entryLevel: "STANDARD BUILDER ENTRY (Members) - $2,500",
    paymentMethod: "Credit Card",
    signature:
      "https://mcbia.org/index.php?gf-signature=6a60cd94cd1ae4.77088911&form-id=47&field-id=41&hash=99247579da5475ff0ce7b17a1447ff27c9c1915d129ceff7d70a624e732fbed4",
    billingName: "Nicole Cortez",
    receiptEmail: "nicole@securebuilt.com",
    billingAddress: "PO BOX 2765, Ocala, FL 34478",
    frontElevation: "/parade-entries/2026/secure-built-rutherford-home.jpg",
    logo: "/parade-entries/2026/secure-built-logo.png",
    floorPlan: null,
    details: {
      entryId: "2441",
      total: "2575",
      features: [
        "3 bedrooms, 3 bathrooms, 2-car garage, and office",
        "Modern farmhouse meets country living",
        "Open living area with deep coffered tray ceiling",
        "Chef's kitchen with quartz countertops and walk-in pantry",
        "Owner's suite with large island in closet",
        "Spa bath with soaking tub and dual shower",
        "Oversized lanai with pool bath access",
        "Oversized 2-car garage",
        "Secure Built 2-10 warranty",
      ],
    },
  },
  {
    id: "entry_brije_fisher",
    createdAt: new Date("2026-08-02T19:38:00-04:00"),
    status: "APPROVED",
    contactName: "Wendy Fisher",
    contactPhone: "407-794-0000",
    contactEmail: "wendy@brije.com",
    builderName: "BRIJE LLC",
    builderContact: "Wendy Fisher",
    builderPhone: "407-794-0000",
    builderEmail: "wendy@brije.com",
    website: "www.brije.com",
    officeAddress: "42 S Magnolia Ave, Ocala, FL 34471",
    license: "CGC1507996",
    modelName: "The Aspen",
    sqftLiving: "5552",
    sqftTotal: "8073",
    beds: "4",
    baths: "5",
    garage: "4",
    subdivision: null,
    modelAddress: "14951 SE 60th St, Morriston, FL 32668",
    price: "$2,750,000",
    buildType: "Custom Home",
    staged: "Yes",
    entryLevel: "",
    paymentMethod: "Check",
    signature: "",
    billingName: "Wendy Fisher",
    receiptEmail: null,
    billingAddress: null,
    frontElevation: "/parade-entries/2026/brije-home.png",
    logo: null,
    floorPlan: null,
    details: {
      entryId: "2462",
      listPrice: "$3,200,000",
      features: [
        "Modern farmhouse on 12 acres",
        "Grand entry with floor-to-ceiling windows",
        "Great family room with fireplace",
        "Walk-in butler's pantry",
        "Freedom room",
        "AI-powered smart home",
        "Zen outdoor garden",
        "Laundry room inside primary suite",
        "Pool and outdoor living space",
        "Dual 2-car garage",
      ],
      subcontractors: [
        "Pool - Agua Pools",
        "Plumbing - Reputable Plumbing",
        "Windows - Prime Windows and Doors",
        "Concrete - Del Zotto Concrete",
        "Roof - Bushnell Truss",
        "HVAC - SunKool AC",
      ],
      otherSubcontractors: [
        "Manning Building Supplies - Trim and lumber",
        "ABC Supply - Siding",
        "BCS Insulation - Insulation",
        "Bushnell Truss - Trusses",
        "D&D Garage Doors - Garage doors and gates",
        "Ocala Flooring - Flooring",
        "84 Lumber - Lumber",
        "A&M Site Development",
      ],
    },
  },
  {
    id: "entry_dr_horton_mckathan",
    createdAt: new Date("2026-08-04T09:00:00-04:00"),
    status: "NEW",
    contactName: "Jennifer McKathan",
    contactPhone: "352-266-4104",
    contactEmail: "jrmckathan@drhorton.com",
    builderName: "D.R. Horton",
    builderContact: "Jennifer McKathan",
    builderPhone: "352-421-1730",
    builderEmail: "jrmckathan@drhorton.com",
    website: "https://www.drhorton.com/florida/west-central-florida",
    officeAddress: null,
    license: "",
    modelName: "",
    sqftLiving: "",
    sqftTotal: "",
    beds: "",
    baths: "",
    garage: "",
    subdivision: null,
    modelAddress: null,
    price: "",
    buildType: "",
    staged: "",
    entryLevel: "",
    paymentMethod: "",
    signature: "",
    billingName: null,
    receiptEmail: null,
    billingAddress: null,
    frontElevation: null,
    logo: null,
    floorPlan: null,
    details: null,
  },
  {
    id: "entry_curington_sebastian",
    createdAt: new Date("2026-08-05T14:14:00-04:00"),
    status: "APPROVED",
    contactName: "Trevor Curington",
    contactPhone: "352-804-9291",
    contactEmail: "trevor@curington.com",
    builderName: "Curington Homes",
    builderContact: "Trevor Curington",
    builderPhone: "352-401-9707",
    builderEmail: "hello@curington.com",
    website: "curingtonhomes.com",
    officeAddress: "2652 NE 24th Street, Ocala, FL 34470",
    license: "CGC1531120",
    modelName: "Sebastian VIII Craftsman Edition",
    sqftLiving: "2322",
    sqftTotal: "3235",
    beds: "4",
    baths: "2",
    garage: "2",
    subdivision: "Irish Acres",
    modelAddress: "8214 NW 17th Circle, Ocala, FL 34475",
    price: "$615,000",
    buildType: "Custom Home",
    staged: "Yes",
    entryLevel: "PREMIER BUILDER ENTRY (Members) - $5,000",
    paymentMethod: "Check",
    signature: "",
    billingName: "Trevor Curington",
    receiptEmail: null,
    billingAddress: null,
    frontElevation: null,
    logo: null,
    floorPlan: null,
    details: {
      entryId: "2479",
      total: "5150",
      features: [
        "Elevated Ceilings",
        "Oversized Windows & Doors",
        "Craftsman Charm",
        "Luxury Kitchen & Baths",
        "Serene Master Retreat",
        "Cozy Electric Fireplace",
        "Elegant Wood Look Tile Flooring",
        "Spacious Walk-In Pantry",
        "Thoughtful Split Floor Plan",
        "Functional Laundry Room",
      ],
      subcontractors: [
        "Tile - Bowen Tile",
        "Windows - Central Florida Window & Door",
        "Doors, Trim, Trusses - Manning Building Supply",
        "Lumber - RoMac Building Supply",
        "Garage Door - Overhead Door Company",
      ],
    },
  },
  {
    id: "entry_ferrer_construction",
    createdAt: new Date("2026-08-05T14:12:00-04:00"),
    status: "NEW",
    contactName: "Brandon Ferrer",
    contactPhone: "352-297-2287",
    contactEmail: "brandon@ferrerconstruction.com",
    builderName: "Ferrer Construction",
    builderContact: "Brandon Ferrer",
    builderPhone: "352-297-2287",
    builderEmail: "brandon@ferrerconstruction.com",
    website: "https://ferrerbuilder.com/",
    officeAddress: "1015 SE 3rd Ave, Ocala, FL 34471",
    license: "CBC029116",
    modelName: "",
    sqftLiving: "",
    sqftTotal: "",
    beds: "",
    baths: "",
    garage: "",
    subdivision: null,
    modelAddress: null,
    price: "",
    buildType: "Custom Home",
    staged: "No",
    entryLevel: "PREMIER BUILDER ENTRY (Members) - $5,000",
    paymentMethod: "Check",
    signature: "",
    billingName: "Brandon Ferrer",
    receiptEmail: null,
    billingAddress: null,
    frontElevation: null,
    logo: null,
    floorPlan: null,
    details: {
      entryId: "2473",
      total: "5150",
      note: "Model home details submitted as N/A — to be provided.",
    },
  },
  {
    id: "entry_luetgert_golden_hills",
    createdAt: new Date("2026-08-05T14:14:00-04:00"),
    status: "APPROVED",
    contactName: "Christopher Luetgert",
    contactPhone: "352-572-7335",
    contactEmail: "info@luetgertdev.com",
    builderName: "Luetgert Development Corp",
    builderContact: "Christopher Luetgert",
    builderPhone: "352-369-8300",
    builderEmail: "info@luetgertdev.com",
    website: "https://www.luetgertdev.com/",
    officeAddress: "505 SE 1st Ave, Ocala, FL 34471",
    license: "CGC1508026",
    modelName: "Golden Hills",
    sqftLiving: "2812",
    sqftTotal: "4604",
    beds: "4",
    baths: "3.5",
    garage: "3",
    subdivision: "Golden Hills & Country Club",
    modelAddress: "5395 NW 76th Court, Ocala, FL 34482",
    price: "$1,400,000",
    buildType: "Spec Home",
    staged: "No",
    entryLevel: "STANDARD BUILDER ENTRY (Members) - $2,500",
    paymentMethod: "PayPal (paid online)",
    signature: "",
    billingName: "Christopher Luetgert",
    receiptEmail: "info@luetgertdev.com",
    billingAddress: "505 SE 1st Ave, Ocala, FL 34471",
    frontElevation: null,
    logo: null,
    floorPlan: null,
    details: {
      entryId: "2478",
      total: "2575",
      listPrice: "$1,995,000",
      listingAgent: "Hanna Pieri, Newgate Realty, LLC",
      features: [
        "Luxury architectural design",
        "Vaulted ceilings",
        "Custom cabinetry",
        "Crysttallo Oro stone countertops",
        "Architectural stained wood beams",
        "Exterior wood ceilings",
        "Poplar wood trim",
        "Professionally designed landscape & hardscape",
        "Gas & wood-burning fireplaces",
        "Custom summer kitchen",
      ],
      payment: {
        paid: true,
        method: "American Express",
        captureId: "9TU13091S05231545",
        amount: "2575.00",
      },
    },
  },
];

export const SPONSOR_ENTRIES = [
  {
    id: "sponsor_kitchenwise",
    createdAt: new Date("2026-08-05T17:36:00-04:00"),
    status: "NEW",
    contactName: "April Goodger",
    contactPhone: "352-325-2777",
    contactEmail: "agoodger@kitchenwise.com",
    companyName: "Kitchen Wise | Closet Wise",
    companyPhone: "352-758-2650",
    companyEmail: "agoodger@kitchenwise.com",
    website: "kitchenwise.com/greater-ocala",
    companyAddress: "2816 CR 523, I-3, Wildwood, FL 34785",
    level: "Half Page Ad Only - $1,200",
    paymentMethod: "Check",
    signature: "",
    billingName: "April Goodger",
    billingEmail: "agoodger@kitchenwise.com",
    billingAddress: null,
    logo: "/parade-entries/2026/kitchen-wise-closet-wise-logo.jpg",
    ad: null,
    details: {
      entryId: "2482",
      total: "12360",
    },
  },
  {
    id: "sponsor_bennett",
    createdAt: new Date("2026-08-05T14:09:00-04:00"),
    status: "APPROVED",
    contactName: "Palmira Bennett",
    contactPhone: "352-861-2300 ext 2",
    contactEmail: "pal@bennettconst.com",
    companyName: "Bennett Custom Homes",
    companyPhone: "352-861-2300",
    companyEmail: "info@bennettconst.com",
    website: "www.loveyourbuilder.com",
    companyAddress: "409 NE 36th Ave, Ocala, FL 34470",
    level: "Full Page Ad Only - $2,000",
    paymentMethod: "Check",
    signature: "",
    billingName: "Palmira Bennett",
    billingEmail: "pal@bennettconst.com",
    billingAddress: null,
    logo: null,
    ad: null,
    details: {
      entryId: "2472",
      total: "2060",
      note: "Wants a 2-page spread (Klodiana advised submitting 1 page twice).",
    },
  },
];
