import type { DB } from "./types";

export const SEED: DB = {
  contest: {
    target: 3,
    prize:
      "Enjoy a three-day stay in a Premium Oceanview Suite at Hammock Beach Golf Resort & Spa, complete with daily breakfast for two at Atlantic Grille. Sponsored by Umpleby Travels.",
  },
  builders: [
    {
      id: "b_brije",
      name: "Brije Homes",
      initials: "BH",
      color: "#116799",
      featured: true,
      phone: "(407) 794-0000",
      website: "brije.com",
      years: 0,
      blurb:
        "Award-winning custom home builder serving Central Florida with a design-first, client-focused building process. Brije Homes' 2026 Parade entry is The Aspen — a 5,552 sq ft modern farmhouse on 12 acres in Morriston.",
      ad: "2026 Featured Builder showcasing The Aspen — a modern farmhouse on 12 acres with an AI-powered smart home, resort-style pool, and outdoor living.",
    },
    {
      id: "b_dr_horton",
      name: "D.R. Horton",
      initials: "DRH",
      color: "#1a2858",
      featured: false,
      phone: "352-421-1730",
      website: "drhorton.com/florida/west-central-florida",
      years: 0,
      blurb:
        "Showcasing the Holden model at Tartan Farms at Winding Oaks for the 2026 Parade of Homes.",
      ad: "Standard Builder Entry - Holden at Tartan Farms at Winding Oaks.",
    },
    {
      id: "b_deltona",
      name: "The Deltona Corporation",
      initials: "DC",
      color: "#f28a20",
      featured: false,
      phone: "352-347-2322",
      website: "deltona.com",
      years: 0,
      blurb:
        "Premier Builder Entry showcasing the Mustang model in Marion Oaks.",
      ad: "Premier Builder Entry - Mustang in Marion Oaks.",
    },
    {
      id: "b_secure_built",
      name: "Secure Built, LLC",
      initials: "SB",
      color: "#d62027",
      featured: false,
      phone: "352-671-9140",
      website: "securebuilt.com",
      years: 0,
      blurb:
        "Custom home builder showcasing the Rutherford Farmhouse in Irish Acres.",
      ad: "Standard Builder Entry - Rutherford Farmhouse in Irish Acres.",
    },
  ],
  neighborhoods: [
    {
      id: "n_tartan_farms",
      name: "Tartan Farms at Winding Oaks",
      city: "Ocala",
      color: "#1a2858",
      img: "/parade-entries/2026/dr-horton-holden-home.jpg",
      blurb:
        "Ocala subdivision featuring D.R. Horton's two-story Holden model for the 2026 Parade.",
      low: 416990,
      high: 416990,
    },
    {
      id: "n_marion_oaks",
      name: "Marion Oaks",
      city: "Ocala",
      color: "#f28a20",
      img: "/parade-entries/2026/deltona-mustang-home.jpg",
      blurb:
        "Southwest Ocala community represented by The Deltona Corporation's Mustang model.",
      low: 350000,
      high: 350000,
    },
    {
      id: "n_irish_acres",
      name: "Irish Acres",
      city: "Ocala",
      color: "#d62027",
      img: "/parade-entries/2026/secure-built-rutherford-home.jpg",
      blurb:
        "Ocala acreage setting for Secure Built's Rutherford Farmhouse custom home.",
      low: 679000,
      high: 699000,
    },
    {
      id: "n_brije_morriston",
      name: "Morriston",
      city: "Morriston",
      color: "#116799",
      img: "/parade-entries/2026/brije-home.png",
      blurb:
        "Twelve-acre countryside setting in Morriston showcasing Brije Homes' custom Aspen modern farmhouse, the 2026 Featured Builder entry.",
      low: 2750000,
      high: 3200000,
    },
  ],
  homes: [
    {
      id: "h_dr_horton_holden",
      name: "Holden",
      builder: "b_dr_horton",
      nb: "n_tartan_farms",
      style: "Spec Home",
      price: 416990,
      beds: 4,
      baths: 3,
      sqft: 3313,
      garage: 2,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: true,
      x: 32,
      y: 50,
      blurb:
        "A two-story, all concrete block spec home in Tartan Farms at Winding Oaks with an open first floor, covered lanai, and smart home technology.",
      features: [
        "Model location: 4416 SW 69th St, Ocala, FL 34474",
        "Open-concept first floor",
        "Covered lanai",
        "Stainless steel dishwasher, electric range, and microwave",
        "2-car garage",
        "10-year RWC home warranty",
        "Smart home technology",
        "Quartz countertops",
        "Luxury vinyl plank flooring in main living areas",
        "Sliding glass door to outdoor patio",
      ],
      imgs: [
        "/parade-entries/2026/dr-horton-holden-home.jpg",
        "/parade-entries/2026/dr-horton-logo.png",
        "/parade-entries/2026/dr-horton-holden-floor-plan.png",
        "/parade-entries/2026/dr-horton-holden-home.jpg",
      ],
    },
    {
      id: "h_deltona_mustang",
      name: "Mustang",
      builder: "b_deltona",
      nb: "n_marion_oaks",
      style: "Spec Home",
      price: 350000,
      beds: 4,
      baths: 2,
      sqft: 2067,
      garage: 2,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: true,
      x: 54,
      y: 65,
      blurb:
        "The Mustang model in Marion Oaks pairs practical living space with upgraded finishes throughout the main living areas.",
      features: [
        "Model location: 356 Marion Oaks Trail, Ocala, FL 34473",
        "Quartz countertops",
        "Tiled shower and tiled tub surround",
        "Luxury vinyl plank flooring throughout main living area",
        "Irrigation system",
        "Garage door opener",
        "Maverick 10-year structural warranty",
        "Wood cabinets with soft-close feature",
        "Large inside laundry room with cabinets",
        "Kitchen island and spacious primary bedroom",
      ],
      imgs: [
        "/parade-entries/2026/deltona-mustang-home.jpg",
        "/parade-entries/2026/deltona-logo.jpg",
        "/parade-entries/2026/deltona-mustang-home.jpg",
        "/parade-entries/2026/deltona-mustang-home.jpg",
      ],
    },
    {
      id: "h_secure_built_rutherford",
      name: "Rutherford Farmhouse",
      builder: "b_secure_built",
      nb: "n_irish_acres",
      style: "Custom Home",
      price: 679000,
      beds: 3,
      baths: 3,
      sqft: 2530,
      garage: 2,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: true,
      x: 75,
      y: 38,
      blurb:
        "Modern farmhouse meets country living in Irish Acres, with open living spaces, a chef's kitchen, and an oversized lanai.",
      features: [
        "Model location: 1764 NW 85th Loop, Ocala, FL 34475",
        "Price as shown: $679,000 - $699,000",
        "3 bedrooms, 3 bathrooms, 2-car garage, and office",
        "Open living area with deep coffered tray ceiling",
        "Chef's kitchen with quartz countertops and walk-in pantry",
        "Owner's suite with large island in closet",
        "Spa bath with soaking tub and dual shower",
        "Oversized lanai with pool bath access",
        "Oversized 2-car garage",
        "Secure Built 2-10 warranty",
      ],
      imgs: [
        "/parade-entries/2026/secure-built-rutherford-home.jpg",
        "/parade-entries/2026/secure-built-logo.png",
        "/parade-entries/2026/secure-built-rutherford-home.jpg",
        "/parade-entries/2026/secure-built-rutherford-home.jpg",
      ],
    },
    {
      id: "h_brije_aspen",
      name: "The Aspen",
      builder: "b_brije",
      nb: "n_brije_morriston",
      style: "Custom Home",
      price: 2750000,
      beds: 4,
      baths: 5,
      sqft: 5552,
      garage: 4,
      checkins: 0,
      rating: 0,
      ratings: 0,
      featured: true,
      x: 18,
      y: 28,
      blurb:
        "Brije Homes' 2026 Featured Builder showcase — a 5,552 sq ft modern farmhouse set on 12 acres in Morriston, with a grand floor-to-ceiling-window entry, AI-powered smart home technology, and a resort-style pool and outdoor living space.",
      features: [
        "Model location: 14951 SE 60th St, Morriston, FL 32668",
        "Price as shown with upgrades (without lot): $2,750,000",
        "8,073 sq ft total under roof on 12 acres",
        "Grand entry with floor-to-ceiling windows",
        "Great family room with fireplace",
        "Walk-in butler's pantry and a dedicated freedom room",
        "AI-powered smart home",
        "Zen outdoor garden",
        "Laundry room inside the primary suite",
        "Pool and outdoor living space",
        "Dual 2-car garages (4 cars)",
      ],
      imgs: [
        "/parade-entries/2026/brije-home.png",
        "/parade-entries/2026/brije-home.png",
        "/parade-entries/2026/brije-home.png",
      ],
    },
  ],
  sponsors: [],
  faqs: [
    {
      q: "When is the 2026 Parade of Homes?",
      a: "The 2026 MCBIA Parade of Homes is scheduled for November 6-8 and November 13-15 across Marion County.",
    },
    {
      q: "Is admission free?",
      a: "Yes. The Parade of Homes is free and open to the public.",
    },
    {
      q: "Where can I find the homes?",
      a: "Use the Homes and Map pages to browse the current 2026 entries. Additional entries and assets will be added as they are received.",
    },
    {
      q: "Who is the featured builder for 2026?",
      a: "[Brije Homes](https://www.brije.com/) is the 2026 Featured Builder. Also named the 2025 Marion County Builder of the Year and recognized with multiple 2025 Parade of Homes awards, Brije Homes creates custom homes with quality craftsmanship and a personalized building experience, helping families across Central Florida build with confidence.",
    },
  ],
  users: [],
  submissions: [],
  notifications: [],
};

export const BUILDER_ENTRIES = [
  {
    id: "entry_dr_horton_holden",
    createdAt: new Date("2026-07-30T11:30:00-04:00"),
    status: "APPROVED",
    contactName: "Jennifer McKathan",
    contactPhone: "352-266-4104",
    contactEmail: "jrmckathan@drhorton.com",
    builderName: "D.R. Horton",
    builderContact: "Jennifer McKathan",
    builderPhone: "352-421-1730",
    builderEmail: "jrmckathan@drhorton.com",
    website: "https://www.drhorton.com/florida/west-central-florida",
    officeAddress: "3300 Southwest 34th Avenue, Ocala, FL 34474",
    license: "CRC057592",
    modelName: "Holden",
    sqftLiving: "3313",
    sqftTotal: "3313",
    beds: "4",
    baths: "3",
    garage: "2",
    subdivision: "Tartan Farms at Winding Oaks",
    modelAddress: "4416 SW 69th St, Ocala, FL 34474",
    price: "$416,990",
    buildType: "Spec Home",
    staged: "Yes",
    entryLevel: "STANDARD BUILDER ENTRY (Members) - $2,500",
    paymentMethod: "Check",
    signature:
      "https://mcbia.org/index.php?gf-signature=6a6b6e1eca2244.06361588&form-id=47&field-id=41&hash=d84c3f3c02f75d84d69a8b94aaeb8f9847e5d299a207d2de0fdb0bc681cca6e3",
    billingName: "Jennifer McKathan",
    receiptEmail: null,
    billingAddress: null,
    frontElevation: "/parade-entries/2026/dr-horton-holden-home.jpg",
    logo: "/parade-entries/2026/dr-horton-logo.png",
    floorPlan: "/parade-entries/2026/dr-horton-holden-floor-plan.png",
    details: {
      entryId: "2456",
      total: "2575",
      features: [
        "Two-story all concrete block home",
        "Open-concept first floor",
        "Covered lanai",
        "Stainless steel dishwasher, electric range, and microwave",
        "2-car garage",
        "10-year RWC home warranty",
        "Smart home technology",
        "Quartz countertops",
        "Luxury vinyl plank flooring in main living areas",
        "Sliding glass door to outdoor patio",
      ],
    },
  },
  {
    id: "entry_deltona_mustang",
    createdAt: new Date("2026-07-27T13:15:00-04:00"),
    status: "APPROVED",
    contactName: "Sara Jackson",
    contactPhone: "352-533-1122",
    contactEmail: "sara.jackson@deltona.com",
    builderName: "The Deltona Corporation",
    builderContact: null,
    builderPhone: "352-347-2322",
    builderEmail: "sara.jackson@deltona.com",
    website: "www.deltona.com",
    officeAddress: "8014 Southwest 135th Street Road, Ocala, FL 34473",
    license: "cbc1261181",
    modelName: "Mustang",
    sqftLiving: "2067",
    sqftTotal: "2786",
    beds: "4",
    baths: "2",
    garage: "2",
    subdivision: "Marion Oaks",
    modelAddress: "356 Marion Oaks Trail, Ocala, FL 34473",
    price: "$350,000",
    buildType: "Spec Home",
    staged: "Yes",
    entryLevel: "PREMIER BUILDER ENTRY (Members) - $5,000",
    paymentMethod: "Credit Card",
    signature:
      "https://mcbia.org/index.php?gf-signature=6a679076039bd5.58424747&form-id=47&field-id=41&hash=82916a52f7f651402382930ad5ed535a848145f29618f6c68f4bfdad75f110c1",
    billingName: "Victoria Pollard",
    receiptEmail: null,
    billingAddress: "8014 Southwest 135th Street Road, Ocala, FL 34473",
    frontElevation: "/parade-entries/2026/deltona-mustang-home.jpg",
    logo: "/parade-entries/2026/deltona-logo.jpg",
    floorPlan: null,
    details: {
      entryId: "2448",
      total: "5150",
      features: [
        "Quartz countertops",
        "Tiled shower and tiled tub surround",
        "Luxury vinyl plank flooring throughout main living area",
        "Irrigation system",
        "Garage door opener",
        "Maverick 10-year structural warranty",
        "Wood cabinets with soft-close feature",
        "Large inside laundry room with cabinets",
        "Kitchen island",
        "Spacious primary bedroom",
      ],
    },
  },
  {
    id: "entry_secure_built_rutherford",
    createdAt: new Date("2026-07-22T10:03:00-04:00"),
    status: "APPROVED",
    contactName: "Nicole Cortez",
    contactPhone: "352-817-5358",
    contactEmail: "nicole@securebuilt.com",
    builderName: "Secure Built, LLC",
    builderContact: "Ryan Gummer",
    builderPhone: "352-671-9140",
    builderEmail: "ryan@securebuilt.com",
    website: "www.securebuilt.com",
    officeAddress: "1764 NW 85th Loop, Ocala, FL 34475",
    license: "CRC1331562",
    modelName: "Rutherford Farmhouse",
    sqftLiving: "2530",
    sqftTotal: "3775",
    beds: "3",
    baths: "3",
    garage: "2",
    subdivision: "Irish Acres",
    modelAddress: "1764 NW 85th Loop, Ocala, FL 34475",
    price: "$679,000 - $699,000",
    buildType: "Custom Home",
    staged: "Yes",
    entryLevel: "STANDARD BUILDER ENTRY (Members) - $2,500",
    paymentMethod: "Credit Card",
    signature:
      "https://mcbia.org/index.php?gf-signature=6a60cd94cd1ae4.77088911&form-id=47&field-id=41&hash=99247579da5475ff0ce7b17a1447ff27c9c1915d129ceff7d70a624e732fbed4",
    billingName: "Nicole Cortez",
    receiptEmail: "nicole@securebuilt.com",
    billingAddress: "PO BOX 2765, Ocala, FL 34478",
    frontElevation: "/parade-entries/2026/secure-built-rutherford-home.jpg",
    logo: "/parade-entries/2026/secure-built-logo.png",
    floorPlan: null,
    details: {
      entryId: "2441",
      total: "2575",
      features: [
        "3 bedrooms, 3 bathrooms, 2-car garage, and office",
        "Modern farmhouse meets country living",
        "Open living area with deep coffered tray ceiling",
        "Chef's kitchen with quartz countertops and walk-in pantry",
        "Owner's suite with large island in closet",
        "Spa bath with soaking tub and dual shower",
        "Oversized lanai with pool bath access",
        "Oversized 2-car garage",
        "Secure Built 2-10 warranty",
      ],
    },
  },
  {
    id: "entry_brije_fisher",
    createdAt: new Date("2026-08-02T19:38:00-04:00"),
    status: "APPROVED",
    contactName: "Wendy Fisher",
    contactPhone: "407-794-0000",
    contactEmail: "wendy@brije.com",
    builderName: "BRIJE LLC",
    builderContact: "Wendy Fisher",
    builderPhone: "407-794-0000",
    builderEmail: "wendy@brije.com",
    website: "www.brije.com",
    officeAddress: "42 S Magnolia Ave, Ocala, FL 34471",
    license: "CGC1507996",
    modelName: "The Aspen",
    sqftLiving: "5552",
    sqftTotal: "8073",
    beds: "4",
    baths: "5",
    garage: "4",
    subdivision: null,
    modelAddress: "14951 SE 60th St, Morriston, FL 32668",
    price: "$2,750,000",
    buildType: "Custom Home",
    staged: "Yes",
    entryLevel: "",
    paymentMethod: "Check",
    signature: "",
    billingName: "Wendy Fisher",
    receiptEmail: null,
    billingAddress: null,
    frontElevation: "/parade-entries/2026/brije-home.png",
    logo: null,
    floorPlan: null,
    details: {
      entryId: "2462",
      listPrice: "$3,200,000",
      features: [
        "Modern farmhouse on 12 acres",
        "Grand entry with floor-to-ceiling windows",
        "Great family room with fireplace",
        "Walk-in butler's pantry",
        "Freedom room",
        "AI-powered smart home",
        "Zen outdoor garden",
        "Laundry room inside primary suite",
        "Pool and outdoor living space",
        "Dual 2-car garage",
      ],
      subcontractors: [
        "Pool - Agua Pools",
        "Plumbing - Reputable Plumbing",
        "Windows - Prime Windows and Doors",
        "Concrete - Del Zotto Concrete",
        "Roof - Bushnell Truss",
        "HVAC - SunKool AC",
      ],
      otherSubcontractors: [
        "Manning Building Supplies - Trim and lumber",
        "ABC Supply - Siding",
        "BCS Insulation - Insulation",
        "Bushnell Truss - Trusses",
        "D&D Garage Doors - Garage doors and gates",
        "Ocala Flooring - Flooring",
        "84 Lumber - Lumber",
        "A&M Site Development",
      ],
    },
  },
  {
    id: "entry_dr_horton_mckathan",
    createdAt: new Date("2026-08-04T09:00:00-04:00"),
    status: "NEW",
    contactName: "Jennifer McKathan",
    contactPhone: "352-266-4104",
    contactEmail: "jrmckathan@drhorton.com",
    builderName: "D.R. Horton",
    builderContact: "Jennifer McKathan",
    builderPhone: "352-421-1730",
    builderEmail: "jrmckathan@drhorton.com",
    website: "https://www.drhorton.com/florida/west-central-florida",
    officeAddress: null,
    license: "",
    modelName: "",
    sqftLiving: "",
    sqftTotal: "",
    beds: "",
    baths: "",
    garage: "",
    subdivision: null,
    modelAddress: null,
    price: "",
    buildType: "",
    staged: "",
    entryLevel: "",
    paymentMethod: "",
    signature: "",
    billingName: null,
    receiptEmail: null,
    billingAddress: null,
    frontElevation: null,
    logo: null,
    floorPlan: null,
    details: null,
  },
];
